export const decorEndpoint: string = '/decor'
export const forgetProductsEndpoint: string = '/forgedProducts'
export const runesEndpoint: string = '/runes'
export const dreamCatchersEndpoint: string = '/dreamCatchers'
export const bijouterieEndpoint: string = '/bijouterie'
export const talismansEndpoint: string = '/talismans'
export const musicEndpoint: string = '/music'
export const amuletsEndpoint: string = '/amulets'
